---
- name: Create a directory if it does not exist
  file:
    path: "{{ vhost_destintion_path }}"
    state: directory
    mode: '0750'

# - name: Prepare nginx all host name variables
#   template:
#     src: templates/hosts_names.conf.j2
#     dest: "{{ vhost_destintion_path }}/hosts_names.conf"
#     mode: "u=r,g=r"

- name: Inlcude tasks
  include_tasks: prepare_vhost/prepare_cert.yaml
  vars:
    vhost: "{{ vhost_params.value }}"
    alias: "{{ vhost_params.key }}"
  loop: "{{ vhosts_params | dict2items }}"
  loop_control:
    loop_var: vhost_params
  when: vhost.cert_file_path is defined

- name: Inlcude tasks
  include_tasks: prepare_vhost/prepare_vhost_conf.yaml
  vars:
    vhost: "{{ vhost_params.value }}"
    alias: "{{ vhost_params.key }}"
  loop: "{{ vhosts_params | dict2items }}"
  loop_control:
    loop_var: vhost_params